import { MediaItem } from '@/types/media';

// Mock data representing a media library with AI-analyzed images
export const mockMediaItems: MediaItem[] = [
  {
    id: '1',
    url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400',
    filename: 'team-meeting-office.jpg',
    type: 'image',
    orientation: 'portrait',
    width: 2400,
    height: 3600,
    size: 2456789,
    uploadedAt: new Date('2025-01-15T10:30:00'),
    uploadedBy: {
      id: 'user1',
      name: 'Sarah Johnson',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't1', label: 'person', confidence: 0.98, category: 'person' },
        { id: 't2', label: 'smiling', confidence: 0.92, category: 'emotion' },
        { id: 't3', label: 'business attire', confidence: 0.88, category: 'object' },
        { id: 't4', label: 'indoor', confidence: 0.95, category: 'scene' },
        { id: 't5', label: 'professional', confidence: 0.91, category: 'scene' },
      ],
      peopleCount: 1,
      dominantColors: ['#2E4057', '#D4A574', '#F5F5F5'],
      suggestedAltTexts: [
        'Professional businessperson smiling confidently in modern office setting',
        'Portrait of a happy professional in business attire against neutral background',
        'Smiling business professional with warm expression in contemporary workspace',
      ],
      faces: [
        { x: 800, y: 600, width: 800, height: 1000, emotion: 'happy' },
      ],
    },
    smartCrops: [],
    tags: ['team', 'professional', 'headshot'],
  },
  {
    id: '2',
    url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=400',
    filename: 'collaborative-workspace.jpg',
    type: 'image',
    orientation: 'landscape',
    width: 4000,
    height: 2667,
    size: 3789456,
    uploadedAt: new Date('2025-01-14T14:20:00'),
    uploadedBy: {
      id: 'user2',
      name: 'Mike Chen',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't6', label: 'laptop', confidence: 0.96, category: 'object' },
        { id: 't7', label: 'notebook', confidence: 0.89, category: 'object' },
        { id: 't8', label: 'coffee cup', confidence: 0.85, category: 'object' },
        { id: 't9', label: 'multiple people', confidence: 0.93, category: 'person' },
        { id: 't10', label: 'collaboration', confidence: 0.90, category: 'scene' },
        { id: 't11', label: 'engaged', confidence: 0.87, category: 'emotion' },
      ],
      peopleCount: 4,
      dominantColors: ['#3A506B', '#5BC0BE', '#F4F4F4'],
      suggestedAltTexts: [
        'Team of four professionals collaborating around laptop in modern office',
        'Diverse group working together with technology and coffee in bright workspace',
        'Collaborative team meeting with laptops and notebooks in contemporary setting',
      ],
      faces: [
        { x: 500, y: 400, width: 300, height: 400, emotion: 'focused' },
        { x: 1200, y: 500, width: 280, height: 380, emotion: 'happy' },
        { x: 2000, y: 450, width: 290, height: 390, emotion: 'engaged' },
        { x: 2800, y: 480, width: 310, height: 410, emotion: 'smiling' },
      ],
    },
    smartCrops: [],
    tags: ['teamwork', 'collaboration', 'technology'],
  },
  {
    id: '3',
    url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400',
    filename: 'nature-mountains-sunset.jpg',
    type: 'image',
    orientation: 'landscape',
    width: 6000,
    height: 4000,
    size: 4567890,
    uploadedAt: new Date('2025-01-13T09:15:00'),
    uploadedBy: {
      id: 'user1',
      name: 'Sarah Johnson',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't12', label: 'mountains', confidence: 0.97, category: 'scene' },
        { id: 't13', label: 'sunset', confidence: 0.94, category: 'scene' },
        { id: 't14', label: 'sky', confidence: 0.99, category: 'scene' },
        { id: 't15', label: 'landscape', confidence: 0.98, category: 'scene' },
        { id: 't16', label: 'outdoor', confidence: 0.99, category: 'scene' },
        { id: 't17', label: 'serene', confidence: 0.89, category: 'emotion' },
      ],
      peopleCount: 0,
      dominantColors: ['#FF6B35', '#4A4E69', '#9A8C98'],
      suggestedAltTexts: [
        'Dramatic sunset over mountain range with golden hour lighting',
        'Scenic mountain landscape bathed in warm sunset colors',
        'Majestic mountain vista with vibrant orange and purple sunset sky',
      ],
    },
    smartCrops: [],
    tags: ['nature', 'landscape', 'inspiration'],
  },
  {
    id: '4',
    url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400',
    filename: 'coding-developer-laptop.jpg',
    type: 'image',
    orientation: 'landscape',
    width: 5184,
    height: 3456,
    size: 3234567,
    uploadedAt: new Date('2025-01-12T16:45:00'),
    uploadedBy: {
      id: 'user3',
      name: 'Alex Rivera',
      avatar: 'https://i.pravatar.cc/150?img=33',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't18', label: 'laptop', confidence: 0.99, category: 'object' },
        { id: 't19', label: 'code', confidence: 0.96, category: 'text' },
        { id: 't20', label: 'keyboard', confidence: 0.98, category: 'object' },
        { id: 't21', label: 'person', confidence: 0.91, category: 'person' },
        { id: 't22', label: 'focused', confidence: 0.88, category: 'emotion' },
        { id: 't23', label: 'technology', confidence: 0.95, category: 'scene' },
      ],
      peopleCount: 1,
      dominantColors: ['#1E1E1E', '#569CD6', '#D4D4D4'],
      suggestedAltTexts: [
        'Software developer typing code on laptop with focused concentration',
        'Close-up of hands coding on laptop keyboard with programming interface visible',
        'Developer working on computer with code editor displayed on screen',
      ],
      faces: [],
    },
    smartCrops: [],
    tags: ['development', 'coding', 'technology'],
  },
  {
    id: '5',
    url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400',
    filename: 'coffee-workspace-plants.jpg',
    type: 'image',
    orientation: 'portrait',
    width: 3168,
    height: 4752,
    size: 2987654,
    uploadedAt: new Date('2025-01-11T11:30:00'),
    uploadedBy: {
      id: 'user2',
      name: 'Mike Chen',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't24', label: 'coffee', confidence: 0.97, category: 'object' },
        { id: 't25', label: 'plants', confidence: 0.93, category: 'object' },
        { id: 't26', label: 'desk', confidence: 0.90, category: 'object' },
        { id: 't27', label: 'notebook', confidence: 0.87, category: 'object' },
        { id: 't28', label: 'cozy', confidence: 0.91, category: 'emotion' },
        { id: 't29', label: 'indoor', confidence: 0.96, category: 'scene' },
      ],
      peopleCount: 0,
      dominantColors: ['#6B4423', '#4A7C59', '#F5E6D3'],
      suggestedAltTexts: [
        'Cozy workspace flat lay with coffee, plants, and notebook on wooden desk',
        'Aesthetic desk setup featuring hot beverage, greenery, and stationery',
        'Warm and inviting workspace arrangement with coffee cup and potted plants',
      ],
    },
    smartCrops: [],
    tags: ['workspace', 'lifestyle', 'aesthetic'],
  },
  {
    id: '6',
    url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400',
    filename: 'team-brainstorm-whiteboard.jpg',
    type: 'image',
    orientation: 'landscape',
    width: 5000,
    height: 3333,
    size: 4123456,
    uploadedAt: new Date('2025-01-10T13:20:00'),
    uploadedBy: {
      id: 'user1',
      name: 'Sarah Johnson',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't30', label: 'whiteboard', confidence: 0.96, category: 'object' },
        { id: 't31', label: 'markers', confidence: 0.88, category: 'object' },
        { id: 't32', label: 'multiple people', confidence: 0.95, category: 'person' },
        { id: 't33', label: 'brainstorming', confidence: 0.92, category: 'scene' },
        { id: 't34', label: 'enthusiastic', confidence: 0.89, category: 'emotion' },
        { id: 't35', label: 'collaborative', confidence: 0.93, category: 'scene' },
      ],
      peopleCount: 3,
      dominantColors: ['#FFFFFF', '#3498DB', '#2C3E50'],
      suggestedAltTexts: [
        'Three team members enthusiastically brainstorming ideas on office whiteboard',
        'Collaborative team session with professionals discussing concepts at whiteboard',
        'Energetic brainstorming meeting with team gathered around whiteboard displaying diagrams',
      ],
      faces: [
        { x: 1000, y: 800, width: 400, height: 500, emotion: 'excited' },
        { x: 2200, y: 900, width: 380, height: 490, emotion: 'engaged' },
        { x: 3500, y: 850, width: 390, height: 510, emotion: 'smiling' },
      ],
    },
    smartCrops: [],
    tags: ['brainstorming', 'teamwork', 'strategy'],
  },
  {
    id: '7',
    url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400',
    filename: 'professional-woman-portrait.jpg',
    type: 'image',
    orientation: 'portrait',
    width: 3000,
    height: 4500,
    size: 2678901,
    uploadedAt: new Date('2025-01-09T15:10:00'),
    uploadedBy: {
      id: 'user3',
      name: 'Alex Rivera',
      avatar: 'https://i.pravatar.cc/150?img=33',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't36', label: 'person', confidence: 0.99, category: 'person' },
        { id: 't37', label: 'confident', confidence: 0.94, category: 'emotion' },
        { id: 't38', label: 'professional attire', confidence: 0.91, category: 'object' },
        { id: 't39', label: 'indoor', confidence: 0.93, category: 'scene' },
        { id: 't40', label: 'glasses', confidence: 0.87, category: 'object' },
      ],
      peopleCount: 1,
      dominantColors: ['#1A1A1A', '#C4A57B', '#F0E6D8'],
      suggestedAltTexts: [
        'Confident professional woman with glasses in business attire',
        'Portrait of businesswoman displaying assured demeanor in office setting',
        'Professional headshot of woman wearing glasses with poised expression',
      ],
      faces: [
        { x: 900, y: 1000, width: 1200, height: 1500, emotion: 'confident' },
      ],
    },
    smartCrops: [],
    tags: ['professional', 'portrait', 'leadership'],
  },
  {
    id: '8',
    url: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400',
    filename: 'video-conference-remote-work.jpg',
    type: 'image',
    orientation: 'landscape',
    width: 6000,
    height: 4000,
    size: 3890123,
    uploadedAt: new Date('2025-01-08T10:05:00'),
    uploadedBy: {
      id: 'user2',
      name: 'Mike Chen',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    altText: undefined,
    aiAnalysis: {
      tags: [
        { id: 't41', label: 'laptop', confidence: 0.98, category: 'object' },
        { id: 't42', label: 'headphones', confidence: 0.92, category: 'object' },
        { id: 't43', label: 'person', confidence: 0.96, category: 'person' },
        { id: 't44', label: 'home office', confidence: 0.89, category: 'scene' },
        { id: 't45', label: 'video call', confidence: 0.94, category: 'scene' },
        { id: 't46', label: 'engaged', confidence: 0.88, category: 'emotion' },
      ],
      peopleCount: 1,
      dominantColors: ['#2D3142', '#BFC0C0', '#FFFFFF'],
      suggestedAltTexts: [
        'Professional participating in video conference call from home office with headphones',
        'Remote worker engaged in virtual meeting on laptop in modern workspace',
        'Person wearing headphones during video call in contemporary home office setup',
      ],
      faces: [
        { x: 2000, y: 1200, width: 800, height: 1000, emotion: 'engaged' },
      ],
    },
    smartCrops: [],
    tags: ['remote work', 'video call', 'productivity'],
  },
];
