import {
  MessageSquare,
  Heart,
  Calendar,
  MapPin,
  Link2,
  Folder,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Home,
  ExternalLink,
  Bell,
  Newspaper,
  Rocket,
  HelpCircle,
  ClipboardList,
  Lightbulb,
  Zap,
  Pin,
  Pencil,
  User,
  Settings,
  FileText,
  LogOut,
  Sun,
  Moon,
  Monitor,
  Bookmark,
  BookmarkCheck,
  LayoutGrid,
  Download,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Monitor as MonitorShare,
  Users,
  Circle,
  Hand,
  ThumbsUp,
  Send,
  MoreVertical,
  X,
  Check,
  AlertCircle,
  Clock,
  Play,
  Square,
  UserPlus,
  Repeat,
  Star,
  Book,
  CheckCircle,
  Briefcase,
  Building,
  Sparkles,
  Lock,
  Rss,
  Globe,
  Plus,
  Search,
  ArrowUpDown,
  List,
  Info,
  Package,
  Gift,
  DollarSign,
  Eye,
} from 'lucide-react';
import { CSSProperties } from 'react';

export type IconName = 'comment' | 'heart' | 'calendar' | 'mapMarker' | 'mapPin' | 'link' | 'folder' | 'chevronDown' | 'chevronLeft' | 'chevronRight' | 'arrowLeft' | 'arrowUp' | 'arrowDown' | 'home' | 'external' | 'bell' | 'chat' | 'feed' | 'rocket' | 'help' | 'clipboard' | 'lightbulb' | 'zap' | 'pin' | 'pencil' | 'user' | 'settings' | 'fileText' | 'logOut' | 'sun' | 'moon' | 'monitor' | 'bookmark' | 'bookmarkFilled' | 'layoutGrid' | 'download' | 'video' | 'videoOff' | 'microphone' | 'microphoneOff' | 'screenShare' | 'users' | 'circle' | 'handRaised' | 'thumbsUp' | 'send' | 'moreVertical' | 'x' | 'check' | 'alertCircle' | 'clock' | 'play' | 'stop' | 'userPlus' | 'repeat' | 'star' | 'book' | 'checkCircle' | 'briefcase' | 'building' | 'sparkles' | 'lock' | 'rss' | 'globe' | 'plus' | 'search' | 'arrowUpDown' | 'list' | 'info' | 'package' | 'gift' | 'dollarSign' | 'eye';

interface IconProps {
  icon: IconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
}

export function Icon({ icon, size = 24, className = '', style }: IconProps) {
  const iconMap = {
    comment: MessageSquare,
    heart: Heart,
    calendar: Calendar,
    mapMarker: MapPin,
    mapPin: MapPin,
    link: Link2,
    folder: Folder,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    arrowLeft: ArrowLeft,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    home: Home,
    external: ExternalLink,
    bell: Bell,
    chat: MessageSquare,
    feed: Newspaper,
    rocket: Rocket,
    help: HelpCircle,
    clipboard: ClipboardList,
    lightbulb: Lightbulb,
    zap: Zap,
    pin: Pin,
    pencil: Pencil,
    user: User,
    settings: Settings,
    fileText: FileText,
    logOut: LogOut,
    sun: Sun,
    moon: Moon,
    monitor: Monitor,
    bookmark: Bookmark,
    bookmarkFilled: BookmarkCheck,
    layoutGrid: LayoutGrid,
    download: Download,
    video: Video,
    videoOff: VideoOff,
    microphone: Mic,
    microphoneOff: MicOff,
    screenShare: MonitorShare,
    users: Users,
    circle: Circle,
    handRaised: Hand,
    thumbsUp: ThumbsUp,
    send: Send,
    moreVertical: MoreVertical,
    x: X,
    check: Check,
    alertCircle: AlertCircle,
    clock: Clock,
    play: Play,
    stop: Square,
    userPlus: UserPlus,
    repeat: Repeat,
    star: Star,
    book: Book,
    checkCircle: CheckCircle,
    briefcase: Briefcase,
    building: Building,
    sparkles: Sparkles,
    lock: Lock,
    rss: Rss,
    globe: Globe,
    plus: Plus,
    search: Search,
    arrowUpDown: ArrowUpDown,
    list: List,
    info: Info,
    package: Package,
    gift: Gift,
    dollarSign: DollarSign,
    eye: Eye,
  };

  const LucideIcon = iconMap[icon];

  if (!LucideIcon) return null;

  return <LucideIcon size={size} className={className} style={style} />;
}
